<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="MainPage.aspx.cs" Inherits="COP_4849FinalProject.MainPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link rel="stylesheet" href="css/custom.css" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <h1 style =" text-align:center">A Search for Protein Function Similarity using Protein Structure Alignment Quality Metrics</h1><br />
        <p style =" text-align:center">By Stephen Bernard Johnson</p><br />
        <h2 style =" text-align:center">Results</h2>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;The Metric Rank analysis technique used the metric scores to
                 generate an ordering among all protein pairs exhibiting a specific protein function(i,e, GOID). From
                 this ordering an average rank was generated by averaging the rank values of all protein pairs that
                 exhibit a specific protein function. Table 2, Table 4, and Table 6 diplay the results of this first
                 stage of analysis. From these results, the best metric for each GOID was determined.</p>
        <div style =" text-align:center" id="controls">
            <asp:Button runat="server" id="proteus300" type="button" OnClick="proteusClick" text="Proteus 300" /><asp:Button runat="server" id="homstrad350" type="button" OnClick="homstradClick" text="Homstrad 150" aria-atomic="True" /><asp:Button runat="server" id="uc300" type="button" OnClick="ucClick" text="UC 300" />
        </div>
        <div style =" text-align:center" id="tableHolder">
            <asp:Label style =" text-align:center" ID="ajaxTable" runat="server"></asp:Label>
        </div>
        <h2 style="text-align:center">
            Metric Rank ANOVA Based Analysis<br />
    
        </h2>
    
    </div>
    </form>
    <p>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        The Metric Rank analysis using ANOVA statistics was used to search for statistical significance among the 10 metrics and 3 datasets. The JMP Pro version 11 software (i.e., subset of the SAS statistical package) was used to perform both ANOVA and Tukey HSD pairwise comparisons. In addition, the statistics were used to test for significance among the GOIDs which exist in at least two proteins (i.e., there is at least one common GOID for the protein pair). In summary, ANOVA statistical analysis was used to validate the following hypothesis:</p>
    <ul>
        <li>There is a significant difference in the protein functiondetection
            capabilities among CM, ESM, MI,SS, RMSD, rRMSD, SI, TMScore, wRMSD,
            and SO across all protein functions exhibited in the Proteus300, 
            Homstrad150, and UC350 datasets (each database bias may be reflected
            as variations in the results).
        </li>
    </ul>
    <asp:HyperLink ID="dataPageLink" runat="server" NavigateUrl="~/dataPage.aspx">Data Set Page</asp:HyperLink>
</body>
</html>
